### ISSUE TITLE
Come countries not resolving correctly

### ISSUE THREAD

**Issue by SimpleHomelab** [rundqvist/docker-ipvanish-tinyproxy#2]
For example, I put in the country code CH for switzerland but none of the server hosts are being resolved correctly. looking at the logs, the container is using "zur" instead of "zrh" in the hostname for zurich. 

would be happy to help to fix this but I am not sure where the "zur" is coming from.

**Comment by rundqvist** [comment]
These names comes from the auto downloaded ipvanish configuration-files. Couldn't repeat it, so I guess they have fixed it.
