### ISSUE TITLE
Options error: You must define TUN/TAP device (--dev)    

### ISSUE THREAD

**Issue by Slarti01** [rundqvist/docker-ipvanish-tinyproxy#3]
Hello,

I'm very new to this so please be gentle, trying to use your docker image to route rtorrent through it

I put in all my details and I continuously get this kind of error

Wed Mar  4 19:46:54 2020 disabling NCP mode (--ncp-disable) because not in P2MP client or server mode                                                        
Options error: You must define TUN/TAP device (--dev)

Any help much appreciated

**Comment by rundqvist** [comment]
Not able to reproduce this one.
It could be a config error in the config files downloaded from ipvanish. If "dev tun" is missing, it would cause this error.
Also, verify that you have "--device=/dev/net/tun" in the "docker run" statement.
